FROM php:8.1.1-apache  
WORKDIR /var/www/php  
COPY . /var/www/php
COPY . /var/www/html
# RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN docker-php-ext-install mysqli
# RUN service apache2 restart

