version: "2"
services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./assets:/docker-entrypoint-initdb.d"
  web:
    depends_on:
      - db
    image: thecodingmachine/php:8.1.1-v4-apache
    volumes:
      - "./:/var/www/html"
    ports:
      - 85:80
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
